name: sim-bbtre-plus
channels:
  - conda-forge
dependencies:
  - numba
  - dask
  - xarray
  - xrft
  - jupyterlab
  - netCDF4
  - h5py
  - pytables
  - gsw
  - matplotlib
  - xgcm
  - xmitgcm
  - xhistogram
